[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "${alacritty_bright_black}"
blue = "${alacritty_bright_blue}"
cyan = "${alacritty_bright_cyan}"
green = "${alacritty_bright_green}"
magenta = "${alacritty_bright_magenta}"
red = "${alacritty_bright_red}"
white = "${alacritty_bright_white}"
yellow = "${alacritty_bright_yellow}"

[colors.normal]
black = "${alacritty_normal_black}"
blue = "${alacritty_normal_blue}"
cyan = "${alacritty_normal_cyan}"
green = "${alacritty_normal_green}"
magenta = "${alacritty_normal_magenta}"
red = "${alacritty_normal_red}"
white = "${alacritty_normal_white}"
yellow = "${alacritty_normal_yellow}"

[colors.primary]
background = "${alacritty_primary_background}"
foreground = "${alacritty_primary_foreground}"

[env]
TERM = "xterm-256color"

[font]
size = ${alacritty_font_size}

[font.bold]
family = "${alacritty_font_bold}"
style = "Bold"

[font.italic]
family = "${alacritty_font_italic}"
style = "Italic"

[font.normal]
family = "${alacritty_font_normal}"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = ${alacritty_window_padding}
y = ${alacritty_window_padding}
