live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x3f3951"
blue = "0xb1baf4"
cyan = "0xb3f4f3"
green = "0xb1f2a7"
magenta = "0xe192ef"
red = "0xe965a5"
white = "0xeee9fc"
yellow = "0xebde76"

[colors.cursor]
cursor = "0xeee9fc"
text = "0xeee9fc"

[colors.normal]
black = "0x282433"
blue = "0xb1baf4"
cyan = "0xb3f4f3"
green = "0xb1f2a7"
magenta = "0xe192ef"
red = "0xe965a5"
white = "0xeee9fc"
yellow = "0xebde76"

[colors.primary]
background = "0x282433"
foreground = "0xeee9fc"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[window.padding]
x = 13
y = 13
